### ISSUE TITLE
compile.py errors out on my machine

### ISSUE THREAD

**Issue by distantcamera** [simondotm/bbc-nula#5]
C:\Users\steve\beebgallery\bbc-nula\gallery>python compile.py
  File "C:\Users\steve\beebgallery\bbc-nula\gallery\compile.py", line 61
    print "Error: Not indexed format"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

I don't really know what has gone wrong, but I'm assuming that it gets to that error message and then fails to print it due to my images not being correctly formatted, though they are 24bit PNG files.

This error happens the first every time running compile.py so it doesn't seem to detect the "mygallery" folder and stop.

**Comment by simondotm** [comment]
@distantcamera this is probably because the script was written for python 2 and hasnt been updated to work with python 3+.

**Comment by distantcamera** [comment]
Yes. I have converted the script to Python 3 using the online converter. It gets further but I don't seem to be able to get it to recognise PIL at all that way. I installed Python2.7 on another machine and everything works as it should.
